workspace:
  base: /go
  path: src/github.com/umputun/docker-logger

pipeline:
  
  build:
    image: golang:1.10-alpine
    commands:
      - cd app
      - export CGO_ENABLED=0
      - export GOOS=linux
      - export GOARCH=amd64
      - go build -v ./...

  docker_master:
    image: plugins/docker
    repo: umputun/docker-logger
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_BRANCH/\//-}
      - latest
    when:
      branch: master
      event: push

  docker_branch:
    image: docker
    commands:
      - docker build .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch:
        exclude: [ master, release/* ]
        event: push


  docker-pullrequest:
    image: docker
    commands:
      - docker build .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: pull_request
