linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - rangeValCopy
      - hugeParam

linters:
  disable-all: true
  enable:
    - staticcheck
    - revive
    - govet
    - unconvert
    - gosec
    - misspell
    - unparam
    - typecheck
    - ineffassign
    - unused
    - stylecheck
    - exportloopref
    - gocritic
    - nakedret
    - gosimple
    - prealloc
    - bodyclose
    - goimports
    - gofmt
    - gochecknoinits
    - errcheck
    - goprintffuncname
    - lll
    - dogsled
    - whitespace
    - gochecknoglobals
    - durationcheck
    - errname
    - exhaustive
    - funlen
    - goconst
    - nestif
    - nilerr
    - tenv
    - usestdlibvars
  fast: false


run:
  concurrency: 8

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - text: "should have a package comment"
      linters:
        - golint
    - text: "package-comments: should have a package comment"
      linters:
        - revive
    - text: "exitAfterDefer:"
      linters:
        - gocritic
    - text: "whyNoLint: include an explanation for nolint directive"
      linters:
        - gocritic
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
  exclude-use-default: false
