language: go
sudo: required

go:
  - "1.10.x"

go_import_path: github.com/umputun/docker-logger

before_install:
  - export DOCKER_HOST='unix:///var/run/docker.sock'
  - go get github.com/mattn/goveralls
  - go get gopkg.in/alecthomas/gometalinter.v2
  - $GOPATH/bin/gometalinter.v2 --install

script:
  - cd app
  - go test ./...
  - $GOPATH/bin/gometalinter.v2 --disable-all --deadline=300s --vendor --enable=vet --enable=vetshadow --enable=golint \
    --enable=staticcheck --enable=ineffassign --enable=goconst --enable=errcheck --enable=unconvert \
    --enable=deadcode  --enable=gosimple --exclude=test --exclude=mock --exclude=vendor ./...
  - go test -cover -coverprofile=.coverprofile $(go list ./...)
  - $GOPATH/bin/goveralls -service=travis-ci -show -coverprofile=.coverprofile
