// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	docker "github.com/fsouza/go-dockerclient"
)

// LogClientMock is a mock implementation of logger.LogClient.
//
//	func TestSomethingThatUsesLogClient(t *testing.T) {
//
//		// make and configure a mocked logger.LogClient
//		mockedLogClient := &LogClientMock{
//			LogsFunc: func(logsOptions docker.LogsOptions) error {
//				panic("mock out the Logs method")
//			},
//		}
//
//		// use mockedLogClient in code that requires logger.LogClient
//		// and then make assertions.
//
//	}
type LogClientMock struct {
	// LogsFunc mocks the Logs method.
	LogsFunc func(logsOptions docker.LogsOptions) error

	// calls tracks calls to the methods.
	calls struct {
		// Logs holds details about calls to the Logs method.
		Logs []struct {
			// LogsOptions is the logsOptions argument value.
			LogsOptions docker.LogsOptions
		}
	}
	lockLogs sync.RWMutex
}

// Logs calls LogsFunc.
func (mock *LogClientMock) Logs(logsOptions docker.LogsOptions) error {
	if mock.LogsFunc == nil {
		panic("LogClientMock.LogsFunc: method is nil but LogClient.Logs was just called")
	}
	callInfo := struct {
		LogsOptions docker.LogsOptions
	}{
		LogsOptions: logsOptions,
	}
	mock.lockLogs.Lock()
	mock.calls.Logs = append(mock.calls.Logs, callInfo)
	mock.lockLogs.Unlock()
	return mock.LogsFunc(logsOptions)
}

// LogsCalls gets all the calls that were made to Logs.
// Check the length with:
//
//	len(mockedLogClient.LogsCalls())
func (mock *LogClientMock) LogsCalls() []struct {
	LogsOptions docker.LogsOptions
} {
	var calls []struct {
		LogsOptions docker.LogsOptions
	}
	mock.lockLogs.RLock()
	calls = mock.calls.Logs
	mock.lockLogs.RUnlock()
	return calls
}
